/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UserController;
import java.awt.Color;
import javax.swing.JOptionPane;
import main.FormLogin;
import model.User;

/**
 *
 * @author Dell
 */
public class FormRegisterAkun extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    int xx,xy;
    public FormRegisterAkun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button_cancle = new javax.swing.JButton();
        label_nama = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        button_daftar = new javax.swing.JButton();
        label_welcome1 = new javax.swing.JLabel();
        label_username1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        label_username2 = new javax.swing.JLabel();
        konfirmasiPassword = new javax.swing.JPasswordField();
        label_password1 = new javax.swing.JLabel();
        loginLink = new javax.swing.JLabel();
        label_welcome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setBackground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/A child character with black hair, large glasses, and a blue shirt, seated on the ground, reading a manga with intense focus. Surrounding the character are more books and loose papers scattered on.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        button_cancle.setBackground(new java.awt.Color(0, 102, 255));
        button_cancle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        button_cancle.setForeground(new java.awt.Color(255, 255, 255));
        button_cancle.setText("X");
        button_cancle.setBorderPainted(false);
        button_cancle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancleActionPerformed(evt);
            }
        });

        label_nama.setBackground(new java.awt.Color(255, 255, 255));
        label_nama.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        label_nama.setForeground(new java.awt.Color(255, 255, 255));
        label_nama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/white.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_cancle)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(label_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_cancle)
                .addGap(27, 27, 27)
                .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_username.setBackground(new java.awt.Color(255, 255, 255));
        label_username.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_username.setForeground(new java.awt.Color(102, 102, 102));
        label_username.setText("Nama");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        label_password.setBackground(new java.awt.Color(255, 255, 255));
        label_password.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_password.setForeground(new java.awt.Color(102, 102, 102));
        label_password.setText("Password");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        button_daftar.setBackground(new java.awt.Color(0, 102, 255));
        button_daftar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        button_daftar.setForeground(new java.awt.Color(255, 255, 255));
        button_daftar.setText("Daftar");
        button_daftar.setToolTipText("");
        button_daftar.setBorderPainted(false);
        button_daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_daftarActionPerformed(evt);
            }
        });

        label_welcome1.setBackground(new java.awt.Color(255, 255, 255));
        label_welcome1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        label_welcome1.setForeground(new java.awt.Color(102, 102, 102));
        label_welcome1.setText("Resgistrasi Akun");

        label_username1.setBackground(new java.awt.Color(255, 255, 255));
        label_username1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_username1.setForeground(new java.awt.Color(102, 102, 102));
        label_username1.setText("Email");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });

        label_username2.setBackground(new java.awt.Color(255, 255, 255));
        label_username2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_username2.setForeground(new java.awt.Color(102, 102, 102));
        label_username2.setText("NIM");

        konfirmasiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiPasswordActionPerformed(evt);
            }
        });

        label_password1.setBackground(new java.awt.Color(255, 255, 255));
        label_password1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_password1.setForeground(new java.awt.Color(102, 102, 102));
        label_password1.setText("Konfirmasi Password");

        loginLink.setBackground(new java.awt.Color(255, 255, 255));
        loginLink.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        loginLink.setForeground(new java.awt.Color(51, 51, 255));
        loginLink.setText("Login di sini");
        loginLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLinkMouseExited(evt);
            }
        });

        label_welcome2.setBackground(new java.awt.Color(255, 255, 255));
        label_welcome2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        label_welcome2.setForeground(new java.awt.Color(102, 102, 102));
        label_welcome2.setText("Sudah punya akun?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_username2)
                                            .addComponent(label_username1)
                                            .addComponent(label_username))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(label_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_password1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                    .addComponent(email)
                                    .addComponent(username)
                                    .addComponent(nim)
                                    .addComponent(konfirmasiPassword)))
                            .addComponent(button_daftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(label_welcome1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(label_welcome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginLink)))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_welcome1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_username1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_username2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konfirmasiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_password1))
                .addGap(28, 28, 28)
                .addComponent(button_daftar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_welcome2)
                    .addComponent(loginLink))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         // TODO add your handling code here:
         xx=evt.getX();
         xy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void button_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_daftarActionPerformed
        // TODO add your handling code here:
        String usernameInput = username.getText();
        String passwordInput = new String(password.getPassword());
        String confirmPasswordInput = new String(konfirmasiPassword.getPassword());
        String emailInput = email.getText();
        String nimInputText = nim.getText();

        if (usernameInput.isEmpty() || passwordInput.isEmpty() || confirmPasswordInput.isEmpty() || emailInput.isEmpty() || nimInputText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi NIM harus angka
        int nimInput;
        try {
            nimInput = Integer.parseInt(nimInputText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "NIM harus berupa angka", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi NIM sudah terdaftar
        UserController userController = new UserController();
        if (userController.isRegistered(nimInput,usernameInput)) {
            JOptionPane.showMessageDialog(this, "NIM atau Username sudah terdaftar, silahkan login", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!passwordInput.equals(confirmPasswordInput)) {
            JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password tidak sesuai", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!emailInput.contains("@stis.ac.id")) {
            JOptionPane.showMessageDialog(this, "Format email tidak valid", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lakukan registrasi
        User newUser = new User(nimInput, usernameInput, passwordInput, 2, emailInput); // Role default 2 untuk pengguna biasa
        boolean registrationSuccess = userController.registerUser(newUser);

        if (registrationSuccess) {
            JOptionPane.showMessageDialog(this, "Registrasi berhasil", "Success", JOptionPane.INFORMATION_MESSAGE);
            new FormLogin().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal, nim sudah digunakan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_daftarActionPerformed

    private void button_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancleActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_button_cancleActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimActionPerformed

    private void konfirmasiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konfirmasiPasswordActionPerformed

    private void loginLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseClicked
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        // Tutup form login saat ini
        this.dispose();
    }//GEN-LAST:event_loginLinkMouseClicked

    private void loginLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseEntered
        // TODO add your handling code here:
        loginLink.setForeground(new Color(0, 0, 128));
    }//GEN-LAST:event_loginLinkMouseEntered

    private void loginLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseExited
        // TODO add your handling code here:
        loginLink.setForeground(Color.BLUE);
    }//GEN-LAST:event_loginLinkMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegisterAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegisterAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegisterAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegisterAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegisterAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancle;
    private javax.swing.JButton button_daftar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField konfirmasiPassword;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_password1;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel label_username1;
    private javax.swing.JLabel label_username2;
    private javax.swing.JLabel label_welcome1;
    private javax.swing.JLabel label_welcome2;
    private javax.swing.JLabel loginLink;
    private javax.swing.JTextField nim;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
