/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.LoggedInUser;
import model.User;
import view.MenuAkun;
import view.MenuDashboard;
import view.MenuManagementEvent;
import view.MenuDaftarPeserta;
import view.MenuExport;

/**
 *
 * @author Dell
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    int xx;
    int xy;
    private User loggedInUser;

    public MenuAdmin(User user) {
        this.loggedInUser = user;
        initComponents();
        updateUserInformation();
    }

    private void updateUserInformation() {
        if (loggedInUser != null) {
            String formattedUsername = capitalizeWords(loggedInUser.getUsername());
            UsernameLabel.setText(formattedUsername);
        }
    }
    
    private String capitalizeWords(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }

        String[] words = str.split("\\s+"); 
        StringBuilder capitalized = new StringBuilder();

        for (String word : words) {
            if (!word.isEmpty()) {
                capitalized.append(Character.toUpperCase(word.charAt(0))); 
                capitalized.append(word.substring(1).toLowerCase()); 
                capitalized.append(" "); 
            }
        }

        return capitalized.toString().trim(); // Hapus spasi berlebih di akhir
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_main2 = new javax.swing.JPanel();
        pn_lineDashboard3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        button_dashboard6 = new javax.swing.JLabel();
        pn_line2Dashboard3 = new javax.swing.JPanel();
        pn_main3 = new javax.swing.JPanel();
        pn_lineManagement = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        button_management = new javax.swing.JLabel();
        pn_line2Management = new javax.swing.JPanel();
        pn_main4 = new javax.swing.JPanel();
        pn_lineRegistrasi = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        button_Daftar = new javax.swing.JLabel();
        pn_line2Registrasi = new javax.swing.JPanel();
        pn_main8 = new javax.swing.JPanel();
        pn_lineExport = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        button_export = new javax.swing.JLabel();
        pn_line2Export = new javax.swing.JPanel();
        pn_main9 = new javax.swing.JPanel();
        pn_lineAkun = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        button_akun = new javax.swing.JLabel();
        pn_line2Akun = new javax.swing.JPanel();
        pn_kanan = new javax.swing.JPanel();
        pn_navbar = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        UsernameLabel = new javax.swing.JLabel();
        Judul1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STISvent");
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 768));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        jLabel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("MENU");

        pn_main2.setBackground(new java.awt.Color(255, 255, 255));

        pn_lineDashboard3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard.png"))); // NOI18N

        button_dashboard6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        button_dashboard6.setForeground(new java.awt.Color(102, 102, 102));
        button_dashboard6.setText("Dashboard");
        button_dashboard6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_dashboard6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_dashboard6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_dashboard6MouseExited(evt);
            }
        });

        pn_line2Dashboard3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2Dashboard3Layout = new javax.swing.GroupLayout(pn_line2Dashboard3);
        pn_line2Dashboard3.setLayout(pn_line2Dashboard3Layout);
        pn_line2Dashboard3Layout.setHorizontalGroup(
            pn_line2Dashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        pn_line2Dashboard3Layout.setVerticalGroup(
            pn_line2Dashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_lineDashboard3Layout = new javax.swing.GroupLayout(pn_lineDashboard3);
        pn_lineDashboard3.setLayout(pn_lineDashboard3Layout);
        pn_lineDashboard3Layout.setHorizontalGroup(
            pn_lineDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineDashboard3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_line2Dashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_dashboard6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_lineDashboard3Layout.setVerticalGroup(
            pn_lineDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineDashboard3Layout.createSequentialGroup()
                .addGroup(pn_lineDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_dashboard6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_lineDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pn_line2Dashboard3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_main2Layout = new javax.swing.GroupLayout(pn_main2);
        pn_main2.setLayout(pn_main2Layout);
        pn_main2Layout.setHorizontalGroup(
            pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_lineDashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pn_main2Layout.setVerticalGroup(
            pn_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_lineDashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pn_main3.setBackground(new java.awt.Color(255, 255, 255));

        pn_lineManagement.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/event.png"))); // NOI18N

        button_management.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        button_management.setForeground(new java.awt.Color(102, 102, 102));
        button_management.setText("Management Event");
        button_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_managementMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_managementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_managementMouseExited(evt);
            }
        });

        pn_line2Management.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2ManagementLayout = new javax.swing.GroupLayout(pn_line2Management);
        pn_line2Management.setLayout(pn_line2ManagementLayout);
        pn_line2ManagementLayout.setHorizontalGroup(
            pn_line2ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        pn_line2ManagementLayout.setVerticalGroup(
            pn_line2ManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_lineManagementLayout = new javax.swing.GroupLayout(pn_lineManagement);
        pn_lineManagement.setLayout(pn_lineManagementLayout);
        pn_lineManagementLayout.setHorizontalGroup(
            pn_lineManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineManagementLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_line2Management, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_management, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_lineManagementLayout.setVerticalGroup(
            pn_lineManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineManagementLayout.createSequentialGroup()
                .addGroup(pn_lineManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_management, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_lineManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pn_line2Management, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_main3Layout = new javax.swing.GroupLayout(pn_main3);
        pn_main3.setLayout(pn_main3Layout);
        pn_main3Layout.setHorizontalGroup(
            pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_lineManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pn_main3Layout.setVerticalGroup(
            pn_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_lineManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pn_main4.setBackground(new java.awt.Color(255, 255, 255));

        pn_lineRegistrasi.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peserta.png"))); // NOI18N

        button_Daftar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        button_Daftar.setForeground(new java.awt.Color(102, 102, 102));
        button_Daftar.setText("Daftar Peserta");
        button_Daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_DaftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_DaftarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_DaftarMouseExited(evt);
            }
        });

        pn_line2Registrasi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2RegistrasiLayout = new javax.swing.GroupLayout(pn_line2Registrasi);
        pn_line2Registrasi.setLayout(pn_line2RegistrasiLayout);
        pn_line2RegistrasiLayout.setHorizontalGroup(
            pn_line2RegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        pn_line2RegistrasiLayout.setVerticalGroup(
            pn_line2RegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_lineRegistrasiLayout = new javax.swing.GroupLayout(pn_lineRegistrasi);
        pn_lineRegistrasi.setLayout(pn_lineRegistrasiLayout);
        pn_lineRegistrasiLayout.setHorizontalGroup(
            pn_lineRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineRegistrasiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_line2Registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_Daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_lineRegistrasiLayout.setVerticalGroup(
            pn_lineRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineRegistrasiLayout.createSequentialGroup()
                .addGroup(pn_lineRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_Daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_lineRegistrasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pn_line2Registrasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_main4Layout = new javax.swing.GroupLayout(pn_main4);
        pn_main4.setLayout(pn_main4Layout);
        pn_main4Layout.setHorizontalGroup(
            pn_main4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_lineRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pn_main4Layout.setVerticalGroup(
            pn_main4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_lineRegistrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pn_main8.setBackground(new java.awt.Color(255, 255, 255));

        pn_lineExport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/register.png"))); // NOI18N

        button_export.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        button_export.setForeground(new java.awt.Color(102, 102, 102));
        button_export.setText("Data Export");
        button_export.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_exportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_exportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_exportMouseExited(evt);
            }
        });

        pn_line2Export.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2ExportLayout = new javax.swing.GroupLayout(pn_line2Export);
        pn_line2Export.setLayout(pn_line2ExportLayout);
        pn_line2ExportLayout.setHorizontalGroup(
            pn_line2ExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        pn_line2ExportLayout.setVerticalGroup(
            pn_line2ExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_lineExportLayout = new javax.swing.GroupLayout(pn_lineExport);
        pn_lineExport.setLayout(pn_lineExportLayout);
        pn_lineExportLayout.setHorizontalGroup(
            pn_lineExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineExportLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_line2Export, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_lineExportLayout.setVerticalGroup(
            pn_lineExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineExportLayout.createSequentialGroup()
                .addGroup(pn_lineExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_lineExportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pn_line2Export, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_main8Layout = new javax.swing.GroupLayout(pn_main8);
        pn_main8.setLayout(pn_main8Layout);
        pn_main8Layout.setHorizontalGroup(
            pn_main8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_lineExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pn_main8Layout.setVerticalGroup(
            pn_main8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_lineExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pn_main9.setBackground(new java.awt.Color(255, 255, 255));

        pn_lineAkun.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userMenu.png"))); // NOI18N

        button_akun.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        button_akun.setForeground(new java.awt.Color(102, 102, 102));
        button_akun.setText("Akun");
        button_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_akunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_akunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_akunMouseExited(evt);
            }
        });

        pn_line2Akun.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2AkunLayout = new javax.swing.GroupLayout(pn_line2Akun);
        pn_line2Akun.setLayout(pn_line2AkunLayout);
        pn_line2AkunLayout.setHorizontalGroup(
            pn_line2AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        pn_line2AkunLayout.setVerticalGroup(
            pn_line2AkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_lineAkunLayout = new javax.swing.GroupLayout(pn_lineAkun);
        pn_lineAkun.setLayout(pn_lineAkunLayout);
        pn_lineAkunLayout.setHorizontalGroup(
            pn_lineAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineAkunLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_line2Akun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_akun, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_lineAkunLayout.setVerticalGroup(
            pn_lineAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_lineAkunLayout.createSequentialGroup()
                .addGroup(pn_lineAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_akun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_lineAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pn_line2Akun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_main9Layout = new javax.swing.GroupLayout(pn_main9);
        pn_main9.setLayout(pn_main9Layout);
        pn_main9Layout.setHorizontalGroup(
            pn_main9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_lineAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pn_main9Layout.setVerticalGroup(
            pn_main9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_main9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pn_lineAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(pn_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_main3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_main4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_main8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_main9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_navbar.setBackground(new java.awt.Color(51, 102, 255));
        pn_navbar.setPreferredSize(new java.awt.Dimension(1266, 70));

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1266, Short.MAX_VALUE)
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(250, 250, 250));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        UsernameLabel.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(102, 102, 102));
        UsernameLabel.setText("Username");

        Judul1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        Judul1.setForeground(new java.awt.Color(102, 102, 102));
        Judul1.setText("Selamat Datang di StisVent,");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("<html> Dengan adanya STISvent, diharapkan proses koordinasi dan manajemen acara di POLSTAT STIS dapat lebih terstruktur dan<br> efektif. Pengguna dapat dengan cepat mengakses informasi terkait acara, termasuk syarat pendaftaran dan jadwal pela-<br>ksanaan acara Sistem ini tidak hanya memudahkan para mahasiswa untuk ikut serta dalam berbagai kegiatan akademis dan non-akademis, tetapi juga membantu pihak administrasi kampus dalam mengatur dan memonitor kegiatan tersebut secara lebih efisien. Dengan demikian, STISvent bukan hanya sekadar aplikasi, tetapi juga sebuah solusi untuk meningkat-<br>kan pengalaman berorganisasi dan berpartisipasi di lingkungan pendidikan tinggi seperti POLSTAT STIS. <br></html> ");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("<html> Aplikasi STISvent yang dikembangkan untuk memenuhi tugas UAS PBO di POLSTAT STIS adalah sebuah sistem manajemen<br> acara yang dirancang khusus untuk memudahkan pengelolaan dan partisipasi dalam berbagai kegiatan dan acara di lin-<br>gkungan kampus. Aplikasi ini memungkinkan pengguna(mahasiswa), untuk melakukan registrasi dan pendaftaran acara<br> dengan mudah melalui platform digital. Selain itu, STISvent juga menyediakan fitur-fitur seperti manajemen data peserta,<br> informasi detail tentang setiap acara, serta integrasi dengan kalender untuk memantau jadwal kegiatan secara efisien.  <br></html> ");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Judul1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UsernameLabel)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Judul1)
                    .addComponent(UsernameLabel))
                .addGap(47, 47, 47)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pn_utama.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        xy=evt.getY();              
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_formMouseDragged

    private void button_dashboard6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_dashboard6MouseClicked
        // TODO add your handling code here:
        pn_lineDashboard3.setBackground(new Color(240,240,240));
        pn_line2Dashboard3.setBackground(new Color(0,102,153));
        pn_utama.removeAll();
        pn_utama.add(new MenuDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
        
    }//GEN-LAST:event_button_dashboard6MouseClicked

    private void button_dashboard6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_dashboard6MouseEntered
        // TODO add your handling code here:
        pn_lineDashboard3.setBackground(new Color(250,250,250));
        pn_line2Dashboard3.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_button_dashboard6MouseEntered

    private void button_dashboard6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_dashboard6MouseExited
        // TODO add your handling code here:
        pn_lineDashboard3.setBackground(new Color(255,255,255));
        pn_line2Dashboard3.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_button_dashboard6MouseExited

    private void button_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_managementMouseClicked
        // TODO add your handling code here:
        pn_lineManagement.setBackground(new Color(240,240,240));
        pn_line2Management.setBackground(new Color(0,102,153));
        pn_utama.removeAll();
        pn_utama.add(new MenuManagementEvent());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_button_managementMouseClicked

    private void button_managementMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_managementMouseEntered
        // TODO add your handling code here:
        pn_lineManagement.setBackground(new Color(250,250,250));
        pn_line2Management.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_button_managementMouseEntered

    private void button_managementMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_managementMouseExited
        // TODO add your handling code here:
        pn_lineManagement.setBackground(new Color(255,255,255));
        pn_line2Management.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_button_managementMouseExited

    private void button_DaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DaftarMouseClicked
        // TODO add your handling code here:
        pn_lineRegistrasi.setBackground(new Color(240,240,240));
        pn_line2Registrasi.setBackground(new Color(0,102,153));
        // Dapatkan informasi pengguna yang sedang login
        User loggedInUser = LoggedInUser.getUser();

        // Periksa apakah pengguna yang sedang login tidak null
        if (loggedInUser != null) {
            // Buat instance MenuAkun dengan pengguna yang sedang login
            MenuDaftarPeserta menuDaftarPeserta = new MenuDaftarPeserta(loggedInUser);

            // Hapus semua komponen dari panel utama
            pn_utama.removeAll();

            // Tambahkan MenuAkun ke panel utama
            pn_utama.add(menuDaftarPeserta);

            // Refresh panel utama
            pn_utama.repaint();
            pn_utama.revalidate();
        } else {
            // Jika tidak ada pengguna yang sedang login, tampilkan pesan error
            JOptionPane.showMessageDialog(this, "Tidak ada pengguna yang sedang login.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_DaftarMouseClicked

    private void button_DaftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DaftarMouseEntered
        // TODO add your handling code here:
        pn_lineRegistrasi.setBackground(new Color(250,250,250));
        pn_line2Registrasi.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_button_DaftarMouseEntered

    private void button_DaftarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DaftarMouseExited
        // TODO add your handling code here:
        pn_lineRegistrasi.setBackground(new Color(255,255,255));
        pn_line2Registrasi.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_button_DaftarMouseExited

    private void button_exportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_exportMouseClicked
        // TODO add your handling code here:
        pn_lineExport.setBackground(new Color(240,240,240));
        pn_line2Export.setBackground(new Color(0,102,153));
        
        User loggedInUser = LoggedInUser.getUser();

        // Periksa apakah pengguna yang sedang login tidak null
        if (loggedInUser != null) {
            // Buat instance MenuAkun dengan pengguna yang sedang login
            MenuExport menuExport = new MenuExport(loggedInUser);

            // Hapus semua komponen dari panel utama
            pn_utama.removeAll();

            // Tambahkan MenuAkun ke panel utama
            pn_utama.add(menuExport);

            // Refresh panel utama
            pn_utama.repaint();
            pn_utama.revalidate();
        } else {
            // Jika tidak ada pengguna yang sedang login, tampilkan pesan error
            JOptionPane.showMessageDialog(this, "Tidak ada pengguna yang sedang login.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_exportMouseClicked

    private void button_exportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_exportMouseEntered
        // TODO add your handling code here:
        pn_lineExport.setBackground(new Color(250,250,250));
        pn_line2Export.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_button_exportMouseEntered

    private void button_exportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_exportMouseExited
        // TODO add your handling code here:
        pn_lineExport.setBackground(new Color(255,255,255));
        pn_line2Export.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_button_exportMouseExited

    private void button_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_akunMouseClicked
        // TODO add your handling code here:
       pn_lineAkun.setBackground(new Color(240, 240, 240));
        pn_line2Akun.setBackground(new Color(0, 102, 153));

        // Dapatkan informasi pengguna yang sedang login
        User loggedInUser = LoggedInUser.getUser();

        // Periksa apakah pengguna yang sedang login tidak null
        if (loggedInUser != null) {
            // Buat instance MenuAkun dengan pengguna yang sedang login
            MenuAkun menuAkun = new MenuAkun(loggedInUser);

            // Hapus semua komponen dari panel utama
            pn_utama.removeAll();

            // Tambahkan MenuAkun ke panel utama
            pn_utama.add(menuAkun);

            // Refresh panel utama
            pn_utama.repaint();
            pn_utama.revalidate();
        } else {
            // Jika tidak ada pengguna yang sedang login, tampilkan pesan error
            JOptionPane.showMessageDialog(this, "Tidak ada pengguna yang sedang login.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_akunMouseClicked

    private void button_akunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_akunMouseEntered
        // TODO add your handling code here:
        pn_lineAkun.setBackground(new Color(250,250,250));
        pn_line2Akun.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_button_akunMouseEntered

    private void button_akunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_akunMouseExited
        // TODO add your handling code here:
        pn_lineAkun.setBackground(new Color(255,255,255));
        pn_line2Akun.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_button_akunMouseExited

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            User loggedInUser = LoggedInUser.getUser();
            public void run() {
                new MenuAdmin(loggedInUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Judul1;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel button_Daftar;
    private javax.swing.JLabel button_akun;
    private javax.swing.JLabel button_dashboard6;
    private javax.swing.JLabel button_export;
    private javax.swing.JLabel button_management;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_line2Akun;
    private javax.swing.JPanel pn_line2Dashboard3;
    private javax.swing.JPanel pn_line2Export;
    private javax.swing.JPanel pn_line2Management;
    private javax.swing.JPanel pn_line2Registrasi;
    private javax.swing.JPanel pn_lineAkun;
    private javax.swing.JPanel pn_lineDashboard3;
    private javax.swing.JPanel pn_lineExport;
    private javax.swing.JPanel pn_lineManagement;
    private javax.swing.JPanel pn_lineRegistrasi;
    private javax.swing.JPanel pn_main2;
    private javax.swing.JPanel pn_main3;
    private javax.swing.JPanel pn_main4;
    private javax.swing.JPanel pn_main8;
    private javax.swing.JPanel pn_main9;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
