/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
/**
 *
 * @author Dell
 */
import controller.EventController;
import controller.PesertaController;
import model.Event;
import model.Peserta;
import model.User;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import strategy.CSVExportStrategy;
import strategy.ExportStrategy;
import strategy.PDFExportStrategy;


public class MenuExport extends javax.swing.JPanel {
    /**
     * Creates new form MenuExport.
     */
    private User loggedInUser;
    private ExportStrategy<Event> eventCSVExportStrategy = new CSVExportStrategy<>();
    private ExportStrategy<Event> eventPDFExportStrategy = new PDFExportStrategy<>();
    private ExportStrategy<Peserta> pesertaCSVExportStrategy = new CSVExportStrategy<>();
    private ExportStrategy<Peserta> pesertaPDFExportStrategy = new PDFExportStrategy<>();

    public MenuExport(User user) {
        initComponents();
        this.loggedInUser = user;

        if (loggedInUser != null && loggedInUser.getRole() != 1) {
            csv_peserta.setVisible(false);
            pdf_peserta.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        csv_event = new javax.swing.JButton();
        pdf_event = new javax.swing.JButton();
        csv_peserta = new javax.swing.JButton();
        pdf_peserta = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Peserta");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(16, 56));

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/register.png"))); // NOI18N
        jLabel16.setText("Menu > Export");

        csv_event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/event.png"))); // NOI18N
        csv_event.setText("Export Data Event to CSV");
        csv_event.setBorderPainted(false);
        csv_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csv_eventActionPerformed(evt);
            }
        });

        pdf_event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/event.png"))); // NOI18N
        pdf_event.setText("Export Data Event to PDF");
        pdf_event.setBorderPainted(false);
        pdf_event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pdf_eventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pdf_eventMouseExited(evt);
            }
        });
        pdf_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf_eventActionPerformed(evt);
            }
        });

        csv_peserta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peserta.png"))); // NOI18N
        csv_peserta.setText("Export Data Peserta to CSV");
        csv_peserta.setBorderPainted(false);
        csv_peserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csv_pesertaActionPerformed(evt);
            }
        });

        pdf_peserta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peserta.png"))); // NOI18N
        pdf_peserta.setText("Export Daftar Peserta to PDF");
        pdf_peserta.setBorderPainted(false);
        pdf_peserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdf_pesertaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Export Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(715, 715, 715)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(csv_peserta, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(csv_event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pdf_event, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pdf_peserta, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {csv_event, csv_peserta, pdf_event, pdf_peserta});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(25, 25, 25)
                .addComponent(jLabel19)
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdf_event, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csv_event, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pdf_peserta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(csv_peserta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {csv_event, csv_peserta, pdf_event, pdf_peserta});

        add(jPanel1, "card2");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void csv_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csv_eventActionPerformed
        // TODO add your handling code here:
         exportEvent(eventCSVExportStrategy, "CSV");
    }//GEN-LAST:event_csv_eventActionPerformed

    private void pdf_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf_eventActionPerformed
        // TODO add your handling code here:
        exportEvent(eventPDFExportStrategy, "PDF");
    }//GEN-LAST:event_pdf_eventActionPerformed

    private void csv_pesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csv_pesertaActionPerformed
        // TODO add your handling code here:
        exportPeserta(pesertaCSVExportStrategy, "CSV");
    }//GEN-LAST:event_csv_pesertaActionPerformed

    private void pdf_pesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdf_pesertaActionPerformed
        // TODO add your handling code here:
        exportPeserta(pesertaPDFExportStrategy, "PDF");
    }//GEN-LAST:event_pdf_pesertaActionPerformed

    private void pdf_eventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdf_eventMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pdf_eventMouseEntered

    private void pdf_eventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdf_eventMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pdf_eventMouseExited
    private void exportEvent(ExportStrategy<Event> exportStrategy, String format) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose Directory to Save " + format);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File directory = fileChooser.getSelectedFile();
            String filePath = directory.getAbsolutePath();

            if (!filePath.toLowerCase().endsWith("." + format.toLowerCase())) {
                filePath += "." + format.toLowerCase();
            }

            try {
                List<Event> eventList = EventController.getAllEventsExport();
                exportStrategy.export(eventList, filePath);
                JOptionPane.showMessageDialog(null, "Event data exported successfully to: " + filePath);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error exporting Event data: " + e.getMessage(), "Export Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void exportPeserta(ExportStrategy<Peserta> exportStrategy, String format) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose Directory to Save " + format);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File directory = fileChooser.getSelectedFile();
            String filePath = directory.getAbsolutePath();

            if (!filePath.toLowerCase().endsWith("." + format.toLowerCase())) {
                filePath += "." + format.toLowerCase();
            }

            try {
                List<Peserta> pesertaList = PesertaController.getAllPeserta();
                exportStrategy.export(pesertaList, filePath);
                JOptionPane.showMessageDialog(null, "Peserta data exported successfully to: " + filePath);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error exporting Peserta data: " + e.getMessage(), "Export Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton csv_event;
    private javax.swing.JButton csv_peserta;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pdf_event;
    private javax.swing.JButton pdf_peserta;
    // End of variables declaration//GEN-END:variables
}
